name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox and any other packages
        run: pip install tox pytest coverage
      - name: Run tox
        run: |
          tox -e py
        continue-on-error: true
      - name: Generate coverage report
        run: |
          coverage xml  # This generates the coverage report after tox runs, even if tox fails
        if: always()  # This ensures the report is generated even if the previous step failed

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: Upload pytest results 
        run: |
          pytest --maxfail=1 --disable-warnings --junitxml=pytest-results.xml
        if: always()  # Ensure this runs regardless of tox or coverage step result

      # Upload the coverage report as an artifact (optional)
      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage.xml  # Path to the coverage XML report
