name: Build and Run Tests

on:
  push:
    branches:
      - master
  workflow_dispatch:  # Manual trigger

jobs:
  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run all test cases
        run: |
          pytest --maxfail=5 --disable-warnings --cov=your_module --cov-report=xml:coverage.xml --junitxml=test-results.xml  # Generate coverage.xml

  build:
    name: Build and Analyze with SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for accurate analysis

      - uses: sonarsource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          extra_args: |
            -Dsonar.tests=.
            -Dsonar.junit.reportPaths=test-results.xml  # Path to pytest results
            -Dsonar.python.coverage.reportPaths=coverage.xml  # Path to coverage report

