name: Manual Test Run

on:
  push:
    branches:
      - master  # or specify the branch you want to listen to
  workflow_dispatch:  # Adds a manual trigger to run the workflow

jobs:
  run_tests:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Replace with your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          

      - name: Run all test cases
        run: |
          pytest --maxfail=5 --disable-warnings  # Adjust options as needed
